/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Salary;

import Dashboard.Home;

/**
 *
 * @author NELAKA HETTIARACHCHI
 */
public class SalaryDashboard extends javax.swing.JFrame {

    /**
     * Creates new form SalaryDashboard
     */
    public SalaryDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        reportGenerate = new javax.swing.JButton();
        addSalary = new javax.swing.JButton();
        removeSalary = new javax.swing.JButton();
        viewSalary = new javax.swing.JButton();
        updateSalary1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deductionSalary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salary Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 370, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 350, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerMgt/customerlogo2-resize.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 110, 90));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Return");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportGenerate.setBackground(new java.awt.Color(51, 51, 51));
        reportGenerate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reportGenerate.setForeground(new java.awt.Color(255, 255, 255));
        reportGenerate.setText("Report Generation");
        reportGenerate.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        reportGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportGenerateActionPerformed(evt);
            }
        });
        jPanel3.add(reportGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 190, 30));

        addSalary.setBackground(new java.awt.Color(51, 51, 51));
        addSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSalary.setForeground(new java.awt.Color(255, 255, 255));
        addSalary.setText("Add Salary");
        addSalary.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        addSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalaryActionPerformed(evt);
            }
        });
        jPanel3.add(addSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 190, 30));

        removeSalary.setBackground(new java.awt.Color(51, 51, 51));
        removeSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeSalary.setForeground(new java.awt.Color(255, 255, 255));
        removeSalary.setText("Remove Salary");
        removeSalary.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        removeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSalaryActionPerformed(evt);
            }
        });
        jPanel3.add(removeSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 190, 30));

        viewSalary.setBackground(new java.awt.Color(51, 51, 51));
        viewSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewSalary.setForeground(new java.awt.Color(255, 255, 255));
        viewSalary.setText("View Salary");
        viewSalary.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        viewSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalaryActionPerformed(evt);
            }
        });
        jPanel3.add(viewSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 190, 30));

        updateSalary1.setBackground(new java.awt.Color(51, 51, 51));
        updateSalary1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateSalary1.setForeground(new java.awt.Color(255, 255, 255));
        updateSalary1.setText("Update Salary");
        updateSalary1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        updateSalary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSalary1ActionPerformed(evt);
            }
        });
        jPanel3.add(updateSalary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 190, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salary/viewimage.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 130));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 130, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salary/updateimg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 120, 130));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salary/addimg.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salary/deleteimg.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 130, 130));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salary/repoimg.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 130, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salary/deducticonimg.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 130, 130));

        deductionSalary.setBackground(new java.awt.Color(51, 51, 51));
        deductionSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deductionSalary.setForeground(new java.awt.Color(255, 255, 255));
        deductionSalary.setText("Deduction Salary");
        deductionSalary.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        deductionSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductionSalaryActionPerformed(evt);
            }
        });
        jPanel3.add(deductionSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Home newHome = new Home();
        newHome.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalaryActionPerformed
        // TODO add your handling code here:
        this.hide();
        Add_Salary newAdd = new Add_Salary();
        newAdd.show();
    }//GEN-LAST:event_addSalaryActionPerformed

    private void viewSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalaryActionPerformed
        // TODO add your handling code here:
        this.hide();
        View_Salary newView = new View_Salary();
        newView.show();
    }//GEN-LAST:event_viewSalaryActionPerformed

    private void updateSalary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSalary1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Update_Salary newUpdated = new Update_Salary();
        newUpdated.show();
    }//GEN-LAST:event_updateSalary1ActionPerformed

    private void removeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSalaryActionPerformed
        // TODO add your handling code here:
        this.hide();
        Delete_Salary newDelete = new Delete_Salary();
        newDelete.show();
    }//GEN-LAST:event_removeSalaryActionPerformed

    private void deductionSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductionSalaryActionPerformed
        // TODO add your handling code here:
        this.hide();
        Salary_Deduction newDeduction = new Salary_Deduction();
        newDeduction.show();
    }//GEN-LAST:event_deductionSalaryActionPerformed

    private void reportGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportGenerateActionPerformed
        // TODO add your handling code here:
        this.hide();
        Salary_Report newrepo = new Salary_Report();
        newrepo.show();
    }//GEN-LAST:event_reportGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSalary;
    private javax.swing.JButton deductionSalary;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton removeSalary;
    private javax.swing.JButton reportGenerate;
    private javax.swing.JButton updateSalary1;
    private javax.swing.JButton viewSalary;
    // End of variables declaration//GEN-END:variables
}
