/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CustomerMgt;

import Dashboard.Home;

/**
 *
 * @author CSN
 */
public class CustomerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form CustomerDashboard
     */
    public CustomerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportgeneration1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        viewcustomer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        addcustomer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        removecustomer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        updatecustomer = new javax.swing.JButton();
        reportgeneration2 = new javax.swing.JButton();
        calendar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        reportgeneration1.setBackground(new java.awt.Color(51, 51, 51));
        reportgeneration1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reportgeneration1.setForeground(new java.awt.Color(255, 255, 255));
        reportgeneration1.setText("Report Generation");
        reportgeneration1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 370, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 350, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerMgt/customerlogo2-resize.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 110, 90));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Return");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 110));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerMgt/reportGen_customer-resize.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 130, 130));

        viewcustomer.setBackground(new java.awt.Color(51, 51, 51));
        viewcustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewcustomer.setForeground(new java.awt.Color(255, 255, 255));
        viewcustomer.setText("View Customer");
        viewcustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        viewcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcustomerActionPerformed(evt);
            }
        });
        jPanel3.add(viewcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 190, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerMgt/add_customer - resize.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, 130));

        addcustomer.setBackground(new java.awt.Color(51, 51, 51));
        addcustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addcustomer.setForeground(new java.awt.Color(255, 255, 255));
        addcustomer.setText("Add Customer");
        addcustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        addcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustomerActionPerformed(evt);
            }
        });
        jPanel3.add(addcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 190, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerMgt/remove_customer-resize.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 130, 130));

        removecustomer.setBackground(new java.awt.Color(51, 51, 51));
        removecustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removecustomer.setForeground(new java.awt.Color(255, 255, 255));
        removecustomer.setText("Remove Customer");
        removecustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        removecustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removecustomerActionPerformed(evt);
            }
        });
        jPanel3.add(removecustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 190, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerMgt/update_customer-resize.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 130, 130));

        updatecustomer.setBackground(new java.awt.Color(51, 51, 51));
        updatecustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatecustomer.setForeground(new java.awt.Color(255, 255, 255));
        updatecustomer.setText("Update Customer");
        updatecustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        updatecustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecustomerActionPerformed(evt);
            }
        });
        jPanel3.add(updatecustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 190, 30));

        reportgeneration2.setBackground(new java.awt.Color(51, 51, 51));
        reportgeneration2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reportgeneration2.setForeground(new java.awt.Color(255, 255, 255));
        reportgeneration2.setText("Report Generation");
        reportgeneration2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        reportgeneration2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportgeneration2ActionPerformed(evt);
            }
        });
        jPanel3.add(reportgeneration2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 190, 30));

        calendar.setBackground(new java.awt.Color(51, 51, 51));
        calendar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calendar.setForeground(new java.awt.Color(255, 255, 255));
        calendar.setText("Calendar");
        calendar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarActionPerformed(evt);
            }
        });
        jPanel3.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 190, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerMgt/calanderimg.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 128, 130));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerMgt/viewimage.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 131, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1030, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Home newHome = new Home();
        newHome.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustomerActionPerformed
        // TODO add your handling code here:
        this.hide();
        Customer_Add newAdd = new Customer_Add();
        newAdd.show();
    }//GEN-LAST:event_addcustomerActionPerformed

    private void updatecustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecustomerActionPerformed
        // TODO add your handling code here:
      this.hide();
        Update_Customer newAdd = new Update_Customer();
        newAdd.show();
    }//GEN-LAST:event_updatecustomerActionPerformed

    private void viewcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcustomerActionPerformed
        // TODO add your handling code here:
        this.hide();
        View_Customerdetails newView = new View_Customerdetails();
        newView.show();
    }//GEN-LAST:event_viewcustomerActionPerformed

    private void removecustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removecustomerActionPerformed
        // TODO add your handling code here:
        this.hide();
        Delete_Customer newAdd = new Delete_Customer();
        newAdd.show();
    }//GEN-LAST:event_removecustomerActionPerformed

    private void reportgeneration2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportgeneration2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        ReportGenaration newView = new ReportGenaration();
        newView.show();
    }//GEN-LAST:event_reportgeneration2ActionPerformed

    private void calendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarActionPerformed
        // TODO add your handling code here:
        this.hide();
        CalenderNote newcalender = new CalenderNote();
        newcalender.show();
    }//GEN-LAST:event_calendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcustomer;
    private javax.swing.JButton calendar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton removecustomer;
    private javax.swing.JButton reportgeneration1;
    private javax.swing.JButton reportgeneration2;
    private javax.swing.JButton updatecustomer;
    private javax.swing.JButton viewcustomer;
    // End of variables declaration//GEN-END:variables
}
